### ISSUE TITLE
建议在左侧视图层次窗口加一个左右滚动的滑动条

### ISSUE THREAD

**Issue by kinkenyuen** [QMUI/LookinServer#23]
当视图层次较深时，深层的控件需要拖拽扩大左侧视图层次窗口，这样一来缩小了主窗口可视化范围

**Comment by hughkli** [comment]
应该…已经是可以左右滑动的吧？如果用的是有线鼠标则底部会有滚动条，如果是苹果鼠标则可以手势左右滑动才对，你再试一下？



&nbsp;


------------------ 原始邮件 ------------------
发件人: Kinken_Yuen <notifications@github.com&gt;
发送时间: 2020年1月4日 17:01
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 建议在左侧视图层次窗口加一个左右滚动的滑动条 (#23)




当视图层次较深时，深层的控件需要拖拽扩大左侧视图层次窗口，这样一来缩小了主窗口可视化范围

**Comment by kinkenyuen** [comment]
> 应该…已经是可以左右滑动的吧？如果用的是有线鼠标则底部会有滚动条，如果是苹果鼠标则可以手势左右滑动才对，你再试一下？ &nbsp;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Kinken_Yuen <notifications@github.com&gt; 发送时间: 2020年1月4日 17:01 收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[QMUI/LookinServer] 建议在左侧视图层次窗口加一个左右滚动的滑动条 (#23) 当视图层次较深时，深层的控件需要拖拽扩大左侧视图层次窗口，这样一来缩小了主窗口可视化范围 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你指的是红框部分有滚动条吗？我用过的是有线鼠标，但是没发现滚动条

![Xnip2020-01-04_17-57-06](https://user-images.githubusercontent.com/41050490/71763851-d73dde80-2f1b-11ea-9cc9-cef334faf3e1.jpg)

**Comment by hughkli** [comment]
好像还真是……看来用有线鼠标时确实有这个 bug，我们会在将来的版本升级中修复它，感谢反馈！



&nbsp;


------------------ 原始邮件 ------------------
发件人: Kinken_Yuen <notifications@github.com&gt;
发送时间: 2020年1月4日 17:59
收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt;
抄送: Li Kai <hughfrakes@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[QMUI/LookinServer] 建议在左侧视图层次窗口加一个左右滚动的滑动条 (#23)



 
应该…已经是可以左右滑动的吧？如果用的是有线鼠标则底部会有滚动条，如果是苹果鼠标则可以手势左右滑动才对，你再试一下？ &nbsp;
 …
 ------------------ 原始邮件 ------------------ 发件人: Kinken_Yuen <notifications@github.com&gt; 发送时间: 2020年1月4日 17:01 收件人: QMUI/LookinServer <LookinServer@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[QMUI/LookinServer] 建议在左侧视图层次窗口加一个左右滚动的滑动条 (#23) 当视图层次较深时，深层的控件需要拖拽扩大左侧视图层次窗口，这样一来缩小了主窗口可视化范围 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你指的是红框部分有滚动条吗？我用过的是有线鼠标，但是没发现滚动条
